### ISSUE TITLE
Task-1 критерии оценки 

### ISSUE THREAD

**Issue by NexGenUA** [rolling-scopes-school/nodejs-course-template#26]
[https://github.com/rolling-scopes-school/nodejs-course-template/blob/master/CROSSCHECK.md](https://github.com/rolling-scopes-school/nodejs-course-template/blob/master/CROSSCHECK.md)

в 3 пункте добавить:  "приложение читает из файла **/process.stdin** "

[https://github.com/rolling-scopes-school/nodejs-course-template/pull/27](https://github.com/rolling-scopes-school/nodejs-course-template/pull/27)

**Comment by AlreadyBored** [comment]
Если переданы все аргументы, чтение происходит из файла, а про чтение из process.stdin есть отдельный пункт
